### ISSUE TITLE
portMapping is not refreshed on restart

### ISSUE THREAD

**Issue by tinedel** [palantir/docker-compose-rule#163]
before restart

$ docker ps
4c7ee9d678c8        2666c3d6_api            "/bin/sh -c 'java -ja"   2 minutes ago       Up 24 seconds       0.0.0.0:32788->8080/tcp                                                   2666c3d6_api_1

after restart
docker.containers().container("api").stop();
docker.containers().container("api").start();

$ docker ps
4c7ee9d678c8        2666c3d6_api            "/bin/sh -c 'java -ja"   8 minutes ago       Up 3 seconds        0.0.0.0:32790->8080/tcp                                                   2666c3d6_api_1

but as portMapping was memoized for container it maps to old port and could not be used

**Comment by joelea** [comment]
Hey @tinedel, thanks for filing. Going to put what I think would be the implementation details below. Realistically, it's going to take a little while for anyone to be in a position to fix this. If you feel like fixing it yourself we'd love to receive the PR.

@hpryce @iamdanfox feels like the sensible way of fixing this is making container cache another `DockerCompose` wrapper rather than this separate thing off the side. Then we can do cache invalidation sensibly, and allow anything using the instance of `DockerCompose` they get handed to get the container caching transparently.

**Comment by fryz** [comment]
Going to close this out in favor of #200
