### ISSUE TITLE
Static DockerComposeRule with dynamic docker ports is not working with multiple integration tests.

### ISSUE THREAD

**Issue by bduisenov** [palantir/docker-compose-rule#196]
The list of `containers` and their `ports` in `DockerComposeRule` is not updated when rule is used as `@ClassRule`. Having dynamic `container ports` and sharing `static DockerComposeRule` between multiple integration tests is not possible, as containers are recreated with different ports on each integration test, but `DockerComposeRule` uses the ports that were assigned in the first integration test.

**Comment by wpoch** [comment]
This is also happening to me. Seems it doesn't refresh the `Container` instance, since despite a new `docker-compose` is spin up on the new tests, the `Container` class of the service is the same as before.

**Comment by jamesneale** [comment]
I am not entirely sure I understand but I am assuming somewhere you have created a single constant static instance of DockerComposeRule and you are referencing that in all of your tests? 

As you have observed, each instance of a DockerComposeRule object is Immutable and only expecting to have before and after called once respectively.

Generally it is recommend to group tests that share the same environment into one class as this reduces overhead. If however you did have some standard set-up that you must share across multiple test classes a simple workaround would be to have a static method (rather than constant) that creates you a new instance of the same DockerComposeRule each time.

**Comment by bduisenov** [comment]
@jamesneale ok, thanks.
