### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by king-jam** [palantir/docker-compose-rule#205]
Is this possible? Would make it more consumable without changes to POM files / settings.xml

**Comment by ravn** [comment]
I would guess that the red tape at Maven Central makes this less desirable before version 1.0.

What is the state of the project, and what is missing to make a version 1.0 release?

**Comment by sarxos** [comment]
@palantir Please deploy to Maven Central. Isn't this project stable enough to be there?

**Comment by uschi2000** [comment]
I don't think we're willing to move from Bintray to Maven Central in the near future. Please use the Bintray location: https://bintray.com/palantir/releases/docker-compose-rule

**Comment by Idriss88** [comment]
Hi,
It will be great if you publish it to Maven Central. This will allow to do not bypass proxy and do not modify maven settings/pom file.
Thanks.

**Comment by sarxos** [comment]
Hi @uschi2000, Bintray copies data from Maven Central and therefore Central seems to be a better place to release because you release artifacts only once and you have them available in all downstream locations (both Maven Central and Bintray and all local or proxy repositories, e.g. Nexus servers used by many companies). Moreover, adding 3rd party repositories into POMs and releasing it into Maven Central is problematic, because Maven Central deployment rules requires all dependencies to be available in Central as well. This is reasonable because anyone would like to end up with artifact with missing dependencies, because some 3rd party repository hosting was dropped/closed/monetized, etc. I didn't verify this, but I suppose - right now, if I would like to release project to Central, and this project would depends on docker-compose-rule, my release would be denied.

**Comment by uschi2000** [comment]
@sarxos, I understand the benefits of Maven Central, however: Our internal OSS repo management tooling is currently set up for the triumvirate GitHub/CircleCI/Bintray, and it would be a non-trivial change to move over to Maven Central. I am happy to kick off a thread internally, but I can't promise any deadline or commitment at this point, sorry.

**Comment by uschi2000** [comment]
Checked with them. They said that Bintray/JCenter was chosen because (at the time, at least) it provided more straightforward integration with automation frameworks and granular permissions. Given the status quo, they currently cannot prioritize moving this over the Maven Central.

That being said, it looks like the Bintray->JCenter synchronization is currently broken, something we need to fix. For Gradle, at least, JCenter is as easy to use to Maven Central.
https://github.com/palantir/docker-compose-rule/issues/207

**Comment by uschi2000** [comment]
Closing this out for now.
